name: vertex build

on:
  push:
    branches: 
      - 'main'
      - 'develop'
      - 'release'
    tags: 'v*'
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger:trx
    - name: Upload Test Results
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: Test Results
        # A file, directory or wildcard pattern that describes what to upload
        path: '**/*.trx'

    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"

    - name: Pack the NuGets
      run: dotnet pack --configuration Release --no-build -o . -p:PackageVersion=$NBGV_SemVer2

    - name: Publish NuGet
      run: |
        cd $GITHUB_WORKSPACE/src
        dotnet nuget push *.*nupkg --api-key ${{ secrets.nugetkey }} --skip-duplicate --source https://api.nuget.org/v3/index.json