name: vertex build

on:
  push:
    branches:
      - "main"
      - "release"
    tags:
      - v*
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
          fetch-depth: 0

      - uses: dotnet/nbgv@master
        with:
          setAllVars: true 
      - run: echo "NuGetPackageVersion $NBGV_NuGetPackageVersion"

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack the NuGets
        run: dotnet pack --configuration Release --no-build -o . -p:PackageVersion=$NBGV_NuGetPackageVersion

      - name: Publish NuGet
        run: |
          cd $GITHUB_WORKSPACE/src
          dotnet nuget push *.*nupkg --api-key ${{ secrets.nugetkey }} --skip-duplicate --source https://api.nuget.org/v3/index.json
